[package]
name = "wasi"
version = "0.5.0"
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
description = "Experimental WASI API bindings for Rust"
edition = "2018"
categories = ["no-std", "wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/CraneStation/rust-wasi"
readme = "README.md"
documentation = "https://docs.rs/wasi"

[dependencies]

[features]
default = ["alloc"]
alloc = []

[badges]
maintenance = { status = "experimental" }
