[package]
name = "generate-raw"
version = "0.0.0"
publish = false
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
edition = "2018"

[dependencies]
heck = "0.3"
witx = { path = "WASI/tools/witx" }
